### ISSUE TITLE
Allow for multiple / dynamic ports

### ISSUE THREAD

**Issue by Dimfred** [estruyf/vscode-remote-control#1]
Hi love this project! Do you mind changing / adding the use of multiple ports?

I sometimes use multiple vscode instances and the second one tries to use the port, which is obviously already in use. 
So extending / converting `port: int`, to `ports: array` would be great.

Further, is it possible to then query the used port and inject it in the terminal environment on startup? 

So basically what I would like to have is:
    
    ports = [
        42,
        1337
    ]
    // Start instance 1 with port 42
    // open terminal with $PORT=42

    // Start instance 2 with port 1337
    // open terminal with $PORT=1337

**Comment by estruyf** [comment]
Thanks for the feedback!

The extension has the option to specify the port per project by setting the `remoteControl.port`: https://github.com/estruyf/vscode-remote-control#extension-settings - I like the idea of dynamic ports, but that might make it harder to create your scripts, as you do not know upfront which instance uses which port.

**Comment by Dimfred** [comment]
Okay cool, that would be a solution indeed, but it would require me to define a separate port in each workspace, which would be more work. 

I use it rightnow only in the vscode internal terminal, where I have zsh with vim mode in in normal mode H L I send editorLeft and editorRight such that I can move from the terminal away, which else wouldn't be possible.

**Comment by estruyf** [comment]
This has now been implemented. You can specify fallback ports with the `remoteControl.fallbacks` setting. It will be available with the new major release.

Thanks @Dimfred for requesting this enhancement.

**Comment by Dimfred** [comment]
Sry for the late response, thats great thanks!
