### ISSUE TITLE
Feature request: get the return value of the task run

### ISSUE THREAD

**Issue by kwavnet** [estruyf/vscode-remote-control#12]
Currently it looks like requesting a task is unidirectional.
It would be cool to have a way to get the actual response from the Thenable executeCommand as a return somehow.

That would enable a proper interaction with the vscode instance.

Would that be within the scope of this extension here?

**Comment by estruyf** [comment]
Hi @kwavnet would you be able to give an example of what you want to achieve?

**Comment by kwavnet** [comment]
We are using some custom commands that return values and it it would be cool to get them out of the vscode instance automatically - in particular we have one that lists all breakpoints https://code.visualstudio.com/api/references/vscode-api#Breakpoint, information that we sadly can't get from anywhere outside of vscode.

It should be checked if something is already set before issuing a commands, as the entire breakpoint API is still a bit shaky IMO.
All that is part of a wider test automation which includes vscode

**Comment by estruyf** [comment]
Ok, I understand it better. I believe it would be doable. We need to await the command execution and return a response via the websocket.

On the execution side where you trigger the remote control its websocket, you also need to be sure to await the response.

**Comment by kwavnet** [comment]
> Ok, I understand it better. I believe it would be doable. We need to await the command execution and return a response via the websocket.
> 
> On the execution side where you trigger the remote control its websocket, you also need to be sure to await the response.

cool and for the requirements, yes that's what I thought

**Comment by estruyf** [comment]
Thanks for your contribution! This just got released in version 1.8.0.
