### ISSUE TITLE
Feat: select random port if default port is already taken

### ISSUE THREAD

**Issue by davidsneighbour** [estruyf/vscode-remote-control#4]
I installed the plugin globally, then opened a second VSCode instance to the following error message:

![20220818-23:01:15-Selection-001](https://user-images.githubusercontent.com/83281/185441663-085a0ac7-2c8a-48a6-8181-2665f118cfc0.png)

I did NOT yet configure anything. I would think the extension to use a different port, if it's impossible to use the same port for multiple instances (I expect two instances of VSCode to be two separate environment?). Maybe use a random port without configuration or a range of ports from which is selected?

I assume it would make more sense maybe, to add some form of onboarding when the extension is loaded the first time in a workspace without configuration that explains how its working and tells users to select a specific port or disable the extension in this specific workspace. I know it's hard to tell if a workspace is configured, there is folder config, workspace config, user config... but somehow the extension should help with the initial configuration tasks.

Maybe even add a note to enable this extension only per workspace and then have an onboarding form to set "conscious" values? 

Ranting here, I know :) Thanks for the hard work!

PS: also the "configure locally" and "configure globally" buttons irritate me slightly... isn't global config exactly what we don't want so we DON'T have two projects use the same port?

PPS: in the farthest sense what I am trying to say is, that this should be a notification "hey, using port Y because port X is used by another VSCode instance. Go to the docs to find out how to configure this properly".

**Comment by estruyf** [comment]
@davidsneighbour I have implemented the changes. Now the extension will start up on a random port and will show that if the other one is already in use.

![image](https://user-images.githubusercontent.com/2900833/188478936-6f1f1aab-aca2-4b9c-a6e0-a646921fadb8.png)
