### ISSUE TITLE
Need to execute terminal commands

### ISSUE THREAD

**Issue by eluce2** [estruyf/vscode-remote-control#7]
I would like to be able to use this extension to execute terminal commands using this engine, but it seems this cannot be done with the command option alone. I think you may need an additional branch, maybe something like this?

```ts
if (wsData.command === "terminal.execute") {
  let terminal = vscode.window.activeTerminal as vscode.Terminal;

  if (terminal && args) {
    terminal.show(true);
    terminal.sendText(args);
  }
}
```

**Comment by estruyf** [comment]
Version 1.5.0 has been released with your enhancement in it. Thanks again @eluce2!
