### ISSUE TITLE
Feature Request: Find out which vscode instance is in focus

### ISSUE THREAD

**Issue by mqnc** [estruyf/vscode-remote-control#9]
I am using this extension for voice coding. If I have multiple instances of vscode running, my commands are sent to the one with the default port, while they should be sent to the instance that has the focus.

I see several options to address this:

- create an option that remote control only accepts commands when the window is in focus, then I can just broadcast commands to the default and all fallback ports
- reflect the port in the vscode window title, where it can easily be read out
- make query-able via ws whether an instance has the focus (this would be the most complicated because it needs a ping pong with each instance before every command)

Would any of this be possible? If you have another idea that doesn't involve modifying your source, I am all ears!

Thanks!

**Comment by mqnc** [comment]
I implemented this myself using the first option. Actually even nicer than that would be if only the vscode instance that has the focus listens on the standard port. But I'm fine with the way it is now.

**Comment by mqnc** [comment]
I created a pull request. I noticed that sometimes commands are not executed until I unfocus and focus the window again :/

**Comment by estruyf** [comment]
@mqnc just noticed the PR and merged it. About the `re-focus`, that might indeed be a problem. Maybe we need to test a bit more to find a better solution to see if a certain window is focussed.

**Comment by mqnc** [comment]
Thanks for merging it! I've been using it the whole time and am not really satisfied with it as I said. The thing is, we really want to avoid that a window that is not in focus receives commands. So when the plugin starts, it assumes that the window doesn't have the focus, although it most likely has. So there is one mandatory refocus after starting vscode, which is already annoying. Then, as I said, it sometimes happens that the vscode.window.onDidChangeWindowState does not fire for some reason. So far I am only aware of that happening when the window gets the focus, not noticing that the focus was lost would be worse (and might have happened without me noticing).

It would be nice if there was some way to query if the vscode window is in focus, rather than an unreliable event when the focus changes. Alternatively, if there was a way to display the RC port in the window title (or any other window property that can be read from the outside), the remotely controlling program can decide what port to send commands to. But as far as I'm aware of, the window.title setting only allows for a very restricted set of dynamic variables.

**Comment by estruyf** [comment]
@mqnc found a `focused` property on the window state: `vscode.window.state.focused`. Let us test it out to see if that works better.

The title is indeed a limitation for extensions.

**Comment by estruyf** [comment]
@mqnc I made a change to the code and pushed it to the DEV branch. Can you test it out and see if that works better?

**Comment by mqnc** [comment]
Seems to work fine, thanks!

**Comment by estruyf** [comment]
Cool! I'll release this.

**Comment by estruyf** [comment]
Version 1.6.0 will be available in a couple of minutes.

**Comment by mqnc** [comment]
Unfortunately it still happens that the window is in foreground but does not receive commands. It seems vscode.window.state.focused is as buggy as the other variant. Seems to be a broader vscode bug then...
